### user signup
POST http://localhost:3030/v1/api/user/register
Content-Type: application/json

{
    "email": "testuser@gmail.com",
    "password": "123"
}

### user login
POST http://localhost:3030/v1/api/user/login
Content-Type: application/json

{
    "option": "testuser@gmail.com",
    "password": "123"
}

### user handle refresh token
POST http://localhost:3030/v1/api/user/refesh
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzEwMjU2ODU0LCJleHAiOjE3MTI4NDg4NTR9.nDBsdIT9pjChb3JfIZtaX3dUWiqBJi0-7RpSSHfPnbs; Path=/; HttpOnly; SameSite=Strict
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzEwMjU2ODU0LCJleHAiOjE3MTAyNTg2NTR9.V0KbE2RIqc2G8F8vA5VDryGyx7W8Rz_-_j2pnUr7NfE

{
    "_id": 2,
    "role": "USER"
}

### user logout
DELETE  http://localhost:3030/v1/api/user/logout
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzEwMzI4NzY4LCJleHAiOjE3MTAzMzA1Njh9.0ZoHTpM8_TjHwibddNuyFt5hlIV-qVN_XrS3d3JtLoE

{
   "_id": 2,
    "role": "USER"
}