### user signup
POST http://localhost:3030/v1/api/user/register
Content-Type: application/json

{
    "email": "testuser@gmail.com",
    "password": "123"
}

### user login
POST http://localhost:3030/v1/api/user/login
Content-Type: application/json

{
    "option": "testuser@gmail.com",
    "password": "123"
}

### user handle refresh token
POST http://localhost:3030/v1/api/user/refesh
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9; Path=/; HttpOnly; SameSite=Strict
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzEwMjUzMjQwLCJleHAiOjE3MTAyNTUwNDB9.eQ9-hUlV21E5l1Pc95TI45ZdrU0tPHsNyacQ7Lit7Sw

{
    "_id": 2,
    "role": "USER"
}

### user logout
DELETE  http://localhost:3030/v1/api/user/logout
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzEwMjUzMjQwLCJleHAiOjE3MTAyNTUwNDB9.eQ9-hUlV21E5l1Pc95TI45ZdrU0tPHsNyacQ7Lit7Sw

{
   "_id": 2,
    "role": "USER"
}